{
 "title": "Labix RS",
 "description": "Metrics of BIRD routing daemon to use with Prometheus for use with https://github.com/czerwonk/bird_exporter",
 "tags": [ "routing" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "# LabIX route server\n\n[AS60247](https://as60247.peeringdb.com/) view via bird exporter"
   }
  },
  {
   "title": "RPKI filtered prefixes",
   "type": "stat",
   "description": "Static render from arouteserver",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bird_protocol_prefix_import_count{instance=\"[2001:7f8:149:1ab:0:6:247:1]:9324\", export_filter=\"REJECT\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total peerings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(state, ip_version) (bird_protocol_up{instance=\"[2001:7f8:149:1ab:0:6:247:1]:9324\"})",
     "legendFormat": "IPv{{ip_version}} {{state}}"
    }
   ]
  },
  { "title": "Import/export", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "RS IPv6 prefixes imported",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_prefix_import_count{ip_version=\"6\", proto=\"BGP\", instance=\"[2001:7f8:149:1ab:0:6:247:1]:9324\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "RS IPv4 prefixes imported",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_prefix_import_count{ip_version=\"4\", proto=\"BGP\", instance=\"[2001:7f8:149:1ab:0:6:247:1]:9324\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "RS IPv6 prefixes exported",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_prefix_export_count{ip_version=\"6\", proto=\"BGP\", instance=\"[2001:7f8:149:1ab:0:6:247:1]:9324\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "RS IPv4 prefixes exported",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_prefix_export_count{ip_version=\"4\", proto=\"BGP\", instance=\"[2001:7f8:149:1ab:0:6:247:1]:9324\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "IPv6 BGP state",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "bird_protocol_up{proto=\"BGP\", instance=\"[2001:7f8:149:1ab:0:6:247:1]:9324\", ip_version=\"6\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "IPv4 BGP state",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "bird_protocol_up{proto=\"BGP\", instance=\"[2001:7f8:149:1ab:0:6:247:1]:9324\", ip_version=\"4\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}