---
- name: Copy apt sources list
  ansible.builtin.copy:
    dest: '/etc/apt/sources.list'
    src: sources.list
    owner: root
    group: root
    mode: '0644'
- name: Run apt update+upgrade
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
  register: apt_result

- name: Log changed packages
  ansible.builtin.debug:
    msg:
      '{% for line in apt_result.stdout_lines
      if "newly installed" in line%}
      {{ line }}
      {% endfor %}'
  when: apt_result.changed == true

- name: Specific apt packages
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-dev
      - python3-virtualenv
      - tmux
      - htop
      - nftables
      - git
      - bgpq4
      - bird2
    state: latest

- name: Update packages to latest
  ansible.builtin.package:
    name: "*"
    state: latest
