---
- name: Copy /etc/bird.conf
  ansible.builtin.copy:
    dest: '/etc/bird.conf'
    src: 'bird.conf'
    owner: root
    group: root
    mode: '0644'
    validate: '/usr/sbin/bird -p -c %s'
  notify: reconfigure bird

- name: Enable bird.service
  ansible.builtin.systemd:
    name: 'bird.service'
    enabled: true
    masked: false
    state: started
