---
- name: Ping host
  ansible.builtin.ping:
  tags:
    - ping

- name: Network Interfaces
  ansible.builtin.import_tasks: interfaces.yml
  become: true
  tags:
    - interfaces
    - deploy

- name: Debian apt packages
  ansible.builtin.import_tasks: apt.yml
  become: true
  tags:
    - apt
    - deploy

- name: BIRD
  ansible.builtin.import_tasks: bird.yml
  become: true
  tags:
    - bird
    - deploy

- name: Copy NFTables config
  become: true
  ansible.builtin.copy:
    src: nftables.conf
    dest: '/etc/nftables.conf'
    owner: root
    group: root
    mode: '0644'
  notify: reload nftables
  tags:
    - nftables
    - deploy

- name: Reboot machine
  become: true
  ansible.builtin.reboot:
  tags:
    - reboot
    - deploy
    - never
